### ISSUE TITLE
Evaluate Towards Data Science's Hacktober Projects

### ISSUE THREAD

**Issue by OscarAblinger** [awesome-global-contributions/awesome-global-contributions#37]
Based upon [Towards Data Science's Article "Make a social impact by contributing to these open source projects"](https://towardsdatascience.com/make-a-social-impact-by-contributing-to-these-open-source-projects-1d6d34e2b8b1), the following lists interesting projects for us to maybe include in our repository.

* [x] Open Machine Learning – transparent and easily accessible ML #38
* [x] AutoFocus – automatically labels animals in a photo trap #39
* [x] Callisto – online reporting system for sexual assault #40
* [x] Oppia – free, high-quality, effective, educational lessons #41
* [ ] Open Street Map iD – OSS street map
* [x] SignDict – sign language repository #45
* [ ] Operation Code – learning veterans how to code
* [x] HOTOSM Website – Open Street Map Website #46
* [x] Open Food – database about food products, ingredients etc. #47
* [x] Diaper – inventory system for diaper banks #56 
* [x] If-Me – community for mental health experience sharing #50 
* [ ] Terrastories – accumulates local stories and traditions
* [ ] All Ready – support humanitarian aid and disaster responses
* [ ] Talk – better commenting experience for journalists
* [x] Ushaidi – processes and collects information about violence #57

I'm aware that many of those projects probably don't really fit the list and as such won't be added. This is just an overview and reminder of them

**Comment by OscarAblinger** [comment]
The rest of the projects are either outdated or - in my opinion - not eligible.
If somebody disagrees, please open a PR or issue :)
