### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AdrienLemaire** [awesome-global-contributions/awesome-global-contributions#7]
<details>
<summary>How to edit the Roadmap</summary>

* Edit this first message to add/remove tasks
* Add `#id` next to tasks to hyperlink tasks to the roadmap
* Check the tasks when they are completed
* Format: `* [ ] Issue title #id @name due/date`

</details>

## August

* [x] Decide project name #4  08/07
* [x] Create organization & Slack #2 @Fandekasp 08/07
* [x] Project qualification outline #5 @AblingerOscar 08/08
* [x] Define YAML Entry Format #3 08/11
* [x] Yaml2Markdown converter #8 @Fandekasp 08/31
* [x] Set up Github Pages @AblingerOscar 

## September

* [ ] Develop HTML Github Pages @AblingerOscar:
  * [x] Automatically list all current projects
  * [ ] Basic filtering of the projects in the list
  * [x] Add basic styling of the project (currently only optimized for mobile)
  * [x] Create Project Yaml Generator page
* [x] Github Actions: auto-update Readme #27 @Fandekasp 09/31
* [ ] Add 15 projects to the repo #29 @Fandekasp 

## Someday

* [ ] Define Markdown entry format #23
* [x] Start collecting first projects data
* [ ] Section "Learning about global issues"
* [ ] Impact score metric
* [ ] Project logo & illustration #1 09/03
* [x] Contribution guidelines #2 09/03
* [ ] Project stars collector
* [ ] Github Issues & PR templates
* [x] Github Checks & Actions
* [ ] Other Website Features
  * [ ] Advanced filtering of the projects in the list
  * [ ] Optimized Desktop styling

**Comment by OscarAblinger** [comment]
The first draft for the project qualification requirements was added in pull request #9.
I've left it open for you to control.

A first draft for the contribution guideline was added in branch [feature/contribution-guideline](https://github.com/awesome-global-contributions/awesome-global-contributions/tree/feature/contribution-guideline).
I didn't create a pull request, because there are still a few TODOs.

**Comment by AdrienLemaire** [comment]
@AblingerOscar I think it's fine to add a PR and merge this document with a badge "Draft" :)
Thanks for your hard work!
